"""PR body templates."""

from __future__ import annotations

from gitoma.analyzers.base import MetricReport
from gitoma.planner.task import TaskPlan


STATUS_EMOJI = {"pass": "✅", "warn": "⚠️", "fail": "❌"}


def build_pr_body(report: MetricReport, plan: TaskPlan, branch: str) -> str:
    """Generate a rich Markdown PR description."""

    # Metric table
    metric_rows = "\n".join(
        f"| {STATUS_EMOJI.get(m.status, '❓')} **{m.display_name}** "
        f"| `{m.score:.0%}` | {m.details} |"
        for m in report.metrics
    )

    # Task list
    task_items = ""
    for task in plan.tasks:
        task_items += f"\n### {task.id}: {task.title}\n"
        task_items += f"> {task.description}\n\n"
        for sub in task.subtasks:
            icon = "✅" if sub.status == "completed" else "🔧"
            sha_ref = f" `{sub.commit_sha[:7]}`" if sub.commit_sha else ""
            task_items += f"- {icon} **{sub.id}** — {sub.title}{sha_ref}\n"
        task_items += "\n"

    # Stats
    completed = plan.completed_tasks
    total = plan.total_tasks
    st_completed = sum(s.status == "completed" for t in plan.tasks for s in t.subtasks)
    st_total = plan.total_subtasks
    overall_before = f"{report.overall_score:.0%}"

    return f"""## 🤖 Gitoma Automated Improvement PR

> Generated by **[Gitoma](https://github.com/fabgpt-coder)** — AI-powered repository improvement agent.
> Branch: `{branch}` | Model: `{plan.llm_model}`

---

## 📊 Repo Health Before → After

| Status | Metric | Score | Details |
|--------|--------|-------|---------|
{metric_rows}

**Overall score before:** `{overall_before}`

---

## 📋 Tasks Completed ({completed}/{total} tasks · {st_completed}/{st_total} subtasks)

{task_items}

---

## ✅ Review Checklist

- [ ] CI passes on this branch
- [ ] No unintended side effects from generated files
- [ ] Commit messages follow Conventional Commits
- [ ] Merge when ready — no further action needed from the bot

---

<sub>🤖 This PR was automatically generated by [Gitoma](https://github.com/fabgpt-coder) using LM Studio · gemma local inference.<br>
Please review carefully before merging. The agent worked hard on this! 💜</sub>
"""


def build_pr_title(repo_name: str, plan: TaskPlan) -> str:
    n_tasks = plan.total_tasks
    n_fixes = sum(
        1 for t in plan.tasks if t.metric in ("ci", "security", "tests")
    )
    if n_fixes:
        return f"🤖 [Gitoma] Improve {repo_name}: {n_tasks} improvements ({n_fixes} critical fixes)"
    return f"🤖 [Gitoma] Improve {repo_name}: {n_tasks} quality improvements"
