# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import supermemory_pb2 as supermemory__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in supermemory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CognitiveEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SurgicalQuery = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/SurgicalQuery',
                request_serializer=supermemory__pb2.SurgicalQueryRequest.SerializeToString,
                response_deserializer=supermemory__pb2.SurgicalQueryResponse.FromString,
                _registered_method=True)
        self.IngestMemories = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/IngestMemories',
                request_serializer=supermemory__pb2.IngestRequest.SerializeToString,
                response_deserializer=supermemory__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestEmbeddingBatch = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/IngestEmbeddingBatch',
                request_serializer=supermemory__pb2.IngestEmbeddingBatchRequest.SerializeToString,
                response_deserializer=supermemory__pb2.IngestEmbeddingBatchResponse.FromString,
                _registered_method=True)
        self.IngestEmbedding = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/IngestEmbedding',
                request_serializer=supermemory__pb2.IngestEmbeddingRequest.SerializeToString,
                response_deserializer=supermemory__pb2.IngestEmbeddingResponse.FromString,
                _registered_method=True)
        self.SearchByEmbedding = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/SearchByEmbedding',
                request_serializer=supermemory__pb2.SearchByEmbeddingRequest.SerializeToString,
                response_deserializer=supermemory__pb2.SearchByEmbeddingResponse.FromString,
                _registered_method=True)
        self.SearchByText = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/SearchByText',
                request_serializer=supermemory__pb2.SearchByTextRequest.SerializeToString,
                response_deserializer=supermemory__pb2.SearchByTextResponse.FromString,
                _registered_method=True)
        self.SearchGroupedByText = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/SearchGroupedByText',
                request_serializer=supermemory__pb2.SearchGroupedByTextRequest.SerializeToString,
                response_deserializer=supermemory__pb2.SearchGroupedByTextResponse.FromString,
                _registered_method=True)
        self.GetMemoryById = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/GetMemoryById',
                request_serializer=supermemory__pb2.GetMemoryByIdRequest.SerializeToString,
                response_deserializer=supermemory__pb2.GetMemoryByIdResponse.FromString,
                _registered_method=True)
        self.UpdateText = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/UpdateText',
                request_serializer=supermemory__pb2.UpdateTextRequest.SerializeToString,
                response_deserializer=supermemory__pb2.UpdateTextResponse.FromString,
                _registered_method=True)
        self.UpdateTextBatch = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/UpdateTextBatch',
                request_serializer=supermemory__pb2.UpdateTextBatchRequest.SerializeToString,
                response_deserializer=supermemory__pb2.UpdateTextBatchResponse.FromString,
                _registered_method=True)
        self.DeleteText = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/DeleteText',
                request_serializer=supermemory__pb2.DeleteTextRequest.SerializeToString,
                response_deserializer=supermemory__pb2.DeleteTextResponse.FromString,
                _registered_method=True)
        self.DeleteTextBatch = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/DeleteTextBatch',
                request_serializer=supermemory__pb2.DeleteTextBatchRequest.SerializeToString,
                response_deserializer=supermemory__pb2.DeleteTextBatchResponse.FromString,
                _registered_method=True)
        self.IngestDocument = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/IngestDocument',
                request_serializer=supermemory__pb2.IngestDocumentRequest.SerializeToString,
                response_deserializer=supermemory__pb2.IngestDocumentResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/ListNamespaces',
                request_serializer=supermemory__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=supermemory__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/DeleteMemory',
                request_serializer=supermemory__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=supermemory__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemoryBatch = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/DeleteMemoryBatch',
                request_serializer=supermemory__pb2.DeleteMemoryBatchRequest.SerializeToString,
                response_deserializer=supermemory__pb2.DeleteMemoryBatchResponse.FromString,
                _registered_method=True)
        self.RestoreMemory = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/RestoreMemory',
                request_serializer=supermemory__pb2.RestoreMemoryRequest.SerializeToString,
                response_deserializer=supermemory__pb2.RestoreMemoryResponse.FromString,
                _registered_method=True)
        self.ListTombstones = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/ListTombstones',
                request_serializer=supermemory__pb2.ListTombstonesRequest.SerializeToString,
                response_deserializer=supermemory__pb2.ListTombstonesResponse.FromString,
                _registered_method=True)
        self.CreateApiKey = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/CreateApiKey',
                request_serializer=supermemory__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=supermemory__pb2.CreateApiKeyResponse.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/RevokeApiKey',
                request_serializer=supermemory__pb2.RevokeApiKeyRequest.SerializeToString,
                response_deserializer=supermemory__pb2.RevokeApiKeyResponse.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/ListApiKeys',
                request_serializer=supermemory__pb2.ListApiKeysRequest.SerializeToString,
                response_deserializer=supermemory__pb2.ListApiKeysResponse.FromString,
                _registered_method=True)
        self.SetRetentionPolicy = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/SetRetentionPolicy',
                request_serializer=supermemory__pb2.SetRetentionPolicyRequest.SerializeToString,
                response_deserializer=supermemory__pb2.SetRetentionPolicyResponse.FromString,
                _registered_method=True)
        self.GetRetentionPolicy = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/GetRetentionPolicy',
                request_serializer=supermemory__pb2.GetRetentionPolicyRequest.SerializeToString,
                response_deserializer=supermemory__pb2.GetRetentionPolicyResponse.FromString,
                _registered_method=True)
        self.RunRetentionScan = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/RunRetentionScan',
                request_serializer=supermemory__pb2.RunRetentionScanRequest.SerializeToString,
                response_deserializer=supermemory__pb2.RunRetentionScanResponse.FromString,
                _registered_method=True)
        self.CompactGraph = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/CompactGraph',
                request_serializer=supermemory__pb2.CompactGraphRequest.SerializeToString,
                response_deserializer=supermemory__pb2.CompactGraphResponse.FromString,
                _registered_method=True)
        self.EngineStats = channel.unary_unary(
                '/supermemory.v1.CognitiveEngine/EngineStats',
                request_serializer=supermemory__pb2.EngineStatsRequest.SerializeToString,
                response_deserializer=supermemory__pb2.EngineStatsResponse.FromString,
                _registered_method=True)


class CognitiveEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SurgicalQuery(self, request, context):
        """Surgical query: text-in, internal ONNX embed, hyperbolic search,
        token-budget-constrained prompt trim. Legacy path — use
        SearchByEmbedding when you bring your own embedder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMemories(self, request, context):
        """Ingest with internal ONNX embedding (or pre-computed, if .embedding
        is non-empty). Legacy path — kept for MCP compatibility. Does NOT
        run the JL + density-warp pipeline of §3.11.2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestEmbeddingBatch(self, request, context):
        """---------------------------------------------------------------
        §3.11.2 pipeline RPCs — bring your own embedder, let Layer0 apply
        the JL projection + Density-to-Radius warp and index the result.
        ---------------------------------------------------------------

        Fit the ingest pipeline on a batch of (id, content, embedding)
        triples and insert the warped vectors into the HNSW index.
        Exactly-once: calling this twice on a server instance returns
        FAILED_PRECONDITION. For continuous ingest, follow up with
        IngestEmbedding.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestEmbedding(self, request, context):
        """Steady-state single-vector ingest through the already-fitted
        pipeline. Returns FAILED_PRECONDITION if IngestEmbeddingBatch has
        not been called yet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByEmbedding(self, request, context):
        """Search by client-provided embedding, routed through the fitted
        pipeline so the query lives on the same warped manifold as the
        indexed documents. Returns FAILED_PRECONDITION if the pipeline is
        unfitted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByText(self, request, context):
        """Search by raw text query. Server encodes the query via its internal
        ONNX pool, routes through the fitted ingest pipeline if one is
        present, and returns structured hits. Designed for MCP / REST
        callers that don't carry their own embedder (Claude Code, simple
        Python orchestrators). Returns INTERNAL if the server started
        without a loadable ONNX model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGroupedByText(self, request, context):
        """Grouped search: single HNSW walk, results distributed into per-tag
        buckets. Returns top-K hits per tag group in one round-trip.
        Designed for consumer agents (gitoma) that need e.g. top-3 from
        each of [plan-shipped, guard-fail, pr-shipped] without issuing N
        separate SearchByText calls. Uses the internal ONNX embedder;
        returns INTERNAL if no model is loaded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryById(self, request, context):
        """Point lookup: fetch a single memory by id (text + metadata).
        Returns NOT_FOUND when the id does not exist or is tombstoned.
        Useful for "show memory X" UIs, replay, and audit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateText(self, request, context):
        """---------------------------------------------------------------
        Text-only content CRUD (touches the TextStore side-car only — no
        HNSW mutation, no vector work). Used for bulk content refresh
        (fixed a typo in a document, replacing boilerplate) and content
        deletion (GDPR erase, deprecated doc) without rebuilding the
        graph node.
        ---------------------------------------------------------------

        Replace the content string for an existing id. The HNSW vector is
        untouched; subsequent searches that return this id will surface the
        new text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTextBatch(self, request, context):
        """Atomic bulk UpdateText over multiple ids.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteText(self, request, context):
        """Delete the text entry for an id. The HNSW node remains (the vector
        is still searchable); hits for a deleted id surface empty content.
        A future release will add soft-delete at the graph level.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTextBatch(self, request, context):
        """Atomic bulk DeleteText over multiple ids.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocument(self, request, context):
        """Chunked document ingest: server splits the raw text into
        overlapping token-sized chunks (default 512 tokens / 64 overlap,
        cl100k_base BPE), embeds each chunk via the internal ONNX pool,
        and inserts them as individual HNSW nodes. The returned
        chunk_ids are deterministic: ingesting the same (source_id, text)
        produces the same ids, so repeated calls are upsert-safe.
        Designed for agent-memory use (Claude Code / MCP): caller hands
        over `README.md` in one shot, Layer0 returns retrievable
        per-paragraph chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """---------------------------------------------------------------
        Multi-tenant: every namespace carries its own HNSW graph, text
        store, §3.11.2 pipeline fit, and L1 cache. Ingests / searches
        scoped to `namespace=A` never touch namespace=B. Unset /
        empty-string `namespace` fields on existing RPCs resolve to
        "default" for backward compatibility. ListNamespaces reports
        all currently-opened namespaces in this server process.
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """---------------------------------------------------------------
        Soft-delete / forget primitives. DeleteMemory tombstones the id
        (search skips it) and wipes its text + metadata — the full
        "forget" operation. The HNSW vector is NOT physically removed
        (true graph compaction is future work); the node still
        participates as a navigational hop but never surfaces as a hit.
        RestoreMemory removes the tombstone; text/metadata stay wiped
        unless the caller re-ingests.
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemoryBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTombstones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """---------------------------------------------------------------
        Per-tenant API-key management. `CreateApiKey` / `RevokeApiKey`
        / `ListApiKeys` all require the caller to hold Admin permission.
        Under `LAYER0_AUTH_MODE=disabled` (the default) every request
        is implicitly Admin, so these RPCs are always reachable — they
        let an operator provision the keystore BEFORE flipping auth on.
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRetentionPolicy(self, request, context):
        """---------------------------------------------------------------
        Per-namespace retention (Fase 11). `SetRetentionPolicy` stores
        a rule (TTL and/or size cap); the server's background scan
        loop applies it by tombstoning expired ids. All three RPCs
        require Admin permission.
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRetentionPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunRetentionScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactGraph(self, request, context):
        """---------------------------------------------------------------
        Graph compaction (Fase 12). Rebuilds the HNSW index over the
        live (non-tombstoned) node set, physically removing tombstoned
        vectors so they no longer participate as navigational hops in
        greedy_search. After a successful compaction the tombstone set
        is cleared — the ids are gone for real, and restoring them via
        `RestoreMemory` becomes a no-op. Admin-only; blocks concurrent
        ingests / searches on the target namespace for the rebuild
        duration (sub-second at N ≤ 10k).
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EngineStats(self, request, context):
        """---------------------------------------------------------------
        Telemetry (Fase 18). Observational read-only snapshot of the
        engine state — per-namespace node count, metric choice,
        tombstone count, pipeline-fit flag, retention policy — plus a
        `ServerInfo` block that carries auth mode, encryption-at-rest
        flag, query-warp mode, ONNX pool status. Designed so an agent
        (or a CLI probe) can ask "what am I talking to?" without
        guessing from env vars.

        Gating: Read permission suffices. Under auth-required mode,
        the per-namespace list is filtered to the caller's
        `allowed_namespaces` — a scoped key does not learn which other
        namespaces exist on the server.
        ---------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CognitiveEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SurgicalQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SurgicalQuery,
                    request_deserializer=supermemory__pb2.SurgicalQueryRequest.FromString,
                    response_serializer=supermemory__pb2.SurgicalQueryResponse.SerializeToString,
            ),
            'IngestMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMemories,
                    request_deserializer=supermemory__pb2.IngestRequest.FromString,
                    response_serializer=supermemory__pb2.IngestResponse.SerializeToString,
            ),
            'IngestEmbeddingBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEmbeddingBatch,
                    request_deserializer=supermemory__pb2.IngestEmbeddingBatchRequest.FromString,
                    response_serializer=supermemory__pb2.IngestEmbeddingBatchResponse.SerializeToString,
            ),
            'IngestEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEmbedding,
                    request_deserializer=supermemory__pb2.IngestEmbeddingRequest.FromString,
                    response_serializer=supermemory__pb2.IngestEmbeddingResponse.SerializeToString,
            ),
            'SearchByEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByEmbedding,
                    request_deserializer=supermemory__pb2.SearchByEmbeddingRequest.FromString,
                    response_serializer=supermemory__pb2.SearchByEmbeddingResponse.SerializeToString,
            ),
            'SearchByText': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByText,
                    request_deserializer=supermemory__pb2.SearchByTextRequest.FromString,
                    response_serializer=supermemory__pb2.SearchByTextResponse.SerializeToString,
            ),
            'SearchGroupedByText': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGroupedByText,
                    request_deserializer=supermemory__pb2.SearchGroupedByTextRequest.FromString,
                    response_serializer=supermemory__pb2.SearchGroupedByTextResponse.SerializeToString,
            ),
            'GetMemoryById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryById,
                    request_deserializer=supermemory__pb2.GetMemoryByIdRequest.FromString,
                    response_serializer=supermemory__pb2.GetMemoryByIdResponse.SerializeToString,
            ),
            'UpdateText': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateText,
                    request_deserializer=supermemory__pb2.UpdateTextRequest.FromString,
                    response_serializer=supermemory__pb2.UpdateTextResponse.SerializeToString,
            ),
            'UpdateTextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTextBatch,
                    request_deserializer=supermemory__pb2.UpdateTextBatchRequest.FromString,
                    response_serializer=supermemory__pb2.UpdateTextBatchResponse.SerializeToString,
            ),
            'DeleteText': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteText,
                    request_deserializer=supermemory__pb2.DeleteTextRequest.FromString,
                    response_serializer=supermemory__pb2.DeleteTextResponse.SerializeToString,
            ),
            'DeleteTextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTextBatch,
                    request_deserializer=supermemory__pb2.DeleteTextBatchRequest.FromString,
                    response_serializer=supermemory__pb2.DeleteTextBatchResponse.SerializeToString,
            ),
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=supermemory__pb2.IngestDocumentRequest.FromString,
                    response_serializer=supermemory__pb2.IngestDocumentResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=supermemory__pb2.ListNamespacesRequest.FromString,
                    response_serializer=supermemory__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=supermemory__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=supermemory__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'DeleteMemoryBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemoryBatch,
                    request_deserializer=supermemory__pb2.DeleteMemoryBatchRequest.FromString,
                    response_serializer=supermemory__pb2.DeleteMemoryBatchResponse.SerializeToString,
            ),
            'RestoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreMemory,
                    request_deserializer=supermemory__pb2.RestoreMemoryRequest.FromString,
                    response_serializer=supermemory__pb2.RestoreMemoryResponse.SerializeToString,
            ),
            'ListTombstones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTombstones,
                    request_deserializer=supermemory__pb2.ListTombstonesRequest.FromString,
                    response_serializer=supermemory__pb2.ListTombstonesResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=supermemory__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=supermemory__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=supermemory__pb2.RevokeApiKeyRequest.FromString,
                    response_serializer=supermemory__pb2.RevokeApiKeyResponse.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=supermemory__pb2.ListApiKeysRequest.FromString,
                    response_serializer=supermemory__pb2.ListApiKeysResponse.SerializeToString,
            ),
            'SetRetentionPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRetentionPolicy,
                    request_deserializer=supermemory__pb2.SetRetentionPolicyRequest.FromString,
                    response_serializer=supermemory__pb2.SetRetentionPolicyResponse.SerializeToString,
            ),
            'GetRetentionPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRetentionPolicy,
                    request_deserializer=supermemory__pb2.GetRetentionPolicyRequest.FromString,
                    response_serializer=supermemory__pb2.GetRetentionPolicyResponse.SerializeToString,
            ),
            'RunRetentionScan': grpc.unary_unary_rpc_method_handler(
                    servicer.RunRetentionScan,
                    request_deserializer=supermemory__pb2.RunRetentionScanRequest.FromString,
                    response_serializer=supermemory__pb2.RunRetentionScanResponse.SerializeToString,
            ),
            'CompactGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactGraph,
                    request_deserializer=supermemory__pb2.CompactGraphRequest.FromString,
                    response_serializer=supermemory__pb2.CompactGraphResponse.SerializeToString,
            ),
            'EngineStats': grpc.unary_unary_rpc_method_handler(
                    servicer.EngineStats,
                    request_deserializer=supermemory__pb2.EngineStatsRequest.FromString,
                    response_serializer=supermemory__pb2.EngineStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'supermemory.v1.CognitiveEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('supermemory.v1.CognitiveEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CognitiveEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SurgicalQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/SurgicalQuery',
            supermemory__pb2.SurgicalQueryRequest.SerializeToString,
            supermemory__pb2.SurgicalQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/IngestMemories',
            supermemory__pb2.IngestRequest.SerializeToString,
            supermemory__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestEmbeddingBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/IngestEmbeddingBatch',
            supermemory__pb2.IngestEmbeddingBatchRequest.SerializeToString,
            supermemory__pb2.IngestEmbeddingBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/IngestEmbedding',
            supermemory__pb2.IngestEmbeddingRequest.SerializeToString,
            supermemory__pb2.IngestEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/SearchByEmbedding',
            supermemory__pb2.SearchByEmbeddingRequest.SerializeToString,
            supermemory__pb2.SearchByEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/SearchByText',
            supermemory__pb2.SearchByTextRequest.SerializeToString,
            supermemory__pb2.SearchByTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGroupedByText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/SearchGroupedByText',
            supermemory__pb2.SearchGroupedByTextRequest.SerializeToString,
            supermemory__pb2.SearchGroupedByTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/GetMemoryById',
            supermemory__pb2.GetMemoryByIdRequest.SerializeToString,
            supermemory__pb2.GetMemoryByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/UpdateText',
            supermemory__pb2.UpdateTextRequest.SerializeToString,
            supermemory__pb2.UpdateTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/UpdateTextBatch',
            supermemory__pb2.UpdateTextBatchRequest.SerializeToString,
            supermemory__pb2.UpdateTextBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/DeleteText',
            supermemory__pb2.DeleteTextRequest.SerializeToString,
            supermemory__pb2.DeleteTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/DeleteTextBatch',
            supermemory__pb2.DeleteTextBatchRequest.SerializeToString,
            supermemory__pb2.DeleteTextBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/IngestDocument',
            supermemory__pb2.IngestDocumentRequest.SerializeToString,
            supermemory__pb2.IngestDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/ListNamespaces',
            supermemory__pb2.ListNamespacesRequest.SerializeToString,
            supermemory__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/DeleteMemory',
            supermemory__pb2.DeleteMemoryRequest.SerializeToString,
            supermemory__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemoryBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/DeleteMemoryBatch',
            supermemory__pb2.DeleteMemoryBatchRequest.SerializeToString,
            supermemory__pb2.DeleteMemoryBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/RestoreMemory',
            supermemory__pb2.RestoreMemoryRequest.SerializeToString,
            supermemory__pb2.RestoreMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTombstones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/ListTombstones',
            supermemory__pb2.ListTombstonesRequest.SerializeToString,
            supermemory__pb2.ListTombstonesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/CreateApiKey',
            supermemory__pb2.CreateApiKeyRequest.SerializeToString,
            supermemory__pb2.CreateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/RevokeApiKey',
            supermemory__pb2.RevokeApiKeyRequest.SerializeToString,
            supermemory__pb2.RevokeApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/ListApiKeys',
            supermemory__pb2.ListApiKeysRequest.SerializeToString,
            supermemory__pb2.ListApiKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRetentionPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/SetRetentionPolicy',
            supermemory__pb2.SetRetentionPolicyRequest.SerializeToString,
            supermemory__pb2.SetRetentionPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRetentionPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/GetRetentionPolicy',
            supermemory__pb2.GetRetentionPolicyRequest.SerializeToString,
            supermemory__pb2.GetRetentionPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunRetentionScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/RunRetentionScan',
            supermemory__pb2.RunRetentionScanRequest.SerializeToString,
            supermemory__pb2.RunRetentionScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/CompactGraph',
            supermemory__pb2.CompactGraphRequest.SerializeToString,
            supermemory__pb2.CompactGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EngineStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supermemory.v1.CognitiveEngine/EngineStats',
            supermemory__pb2.EngineStatsRequest.SerializeToString,
            supermemory__pb2.EngineStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
